/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain;


import de.quinscape.domainql.testdomain.tables.Foo;
import de.quinscape.domainql.testdomain.tables.SourceFive;
import de.quinscape.domainql.testdomain.tables.SourceFour;
import de.quinscape.domainql.testdomain.tables.SourceOne;
import de.quinscape.domainql.testdomain.tables.SourceSeven;
import de.quinscape.domainql.testdomain.tables.SourceSix;
import de.quinscape.domainql.testdomain.tables.SourceThree;
import de.quinscape.domainql.testdomain.tables.SourceTwo;
import de.quinscape.domainql.testdomain.tables.TargetFive;
import de.quinscape.domainql.testdomain.tables.TargetFour;
import de.quinscape.domainql.testdomain.tables.TargetOne;
import de.quinscape.domainql.testdomain.tables.TargetSeven;
import de.quinscape.domainql.testdomain.tables.TargetSix;
import de.quinscape.domainql.testdomain.tables.TargetThree;
import de.quinscape.domainql.testdomain.tables.TargetTwo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.foo</code>.
     */
    public static final Foo FOO = de.quinscape.domainql.testdomain.tables.Foo.FOO;

    /**
     * The table <code>public.source_five</code>.
     */
    public static final SourceFive SOURCE_FIVE = de.quinscape.domainql.testdomain.tables.SourceFive.SOURCE_FIVE;

    /**
     * The table <code>public.source_four</code>.
     */
    public static final SourceFour SOURCE_FOUR = de.quinscape.domainql.testdomain.tables.SourceFour.SOURCE_FOUR;

    /**
     * The table <code>public.source_one</code>.
     */
    public static final SourceOne SOURCE_ONE = de.quinscape.domainql.testdomain.tables.SourceOne.SOURCE_ONE;

    /**
     * The table <code>public.source_seven</code>.
     */
    public static final SourceSeven SOURCE_SEVEN = de.quinscape.domainql.testdomain.tables.SourceSeven.SOURCE_SEVEN;

    /**
     * The table <code>public.source_six</code>.
     */
    public static final SourceSix SOURCE_SIX = de.quinscape.domainql.testdomain.tables.SourceSix.SOURCE_SIX;

    /**
     * The table <code>public.source_three</code>.
     */
    public static final SourceThree SOURCE_THREE = de.quinscape.domainql.testdomain.tables.SourceThree.SOURCE_THREE;

    /**
     * The table <code>public.source_two</code>.
     */
    public static final SourceTwo SOURCE_TWO = de.quinscape.domainql.testdomain.tables.SourceTwo.SOURCE_TWO;

    /**
     * The table <code>public.target_five</code>.
     */
    public static final TargetFive TARGET_FIVE = de.quinscape.domainql.testdomain.tables.TargetFive.TARGET_FIVE;

    /**
     * The table <code>public.target_four</code>.
     */
    public static final TargetFour TARGET_FOUR = de.quinscape.domainql.testdomain.tables.TargetFour.TARGET_FOUR;

    /**
     * The table <code>public.target_one</code>.
     */
    public static final TargetOne TARGET_ONE = de.quinscape.domainql.testdomain.tables.TargetOne.TARGET_ONE;

    /**
     * The table <code>public.target_seven</code>.
     */
    public static final TargetSeven TARGET_SEVEN = de.quinscape.domainql.testdomain.tables.TargetSeven.TARGET_SEVEN;

    /**
     * The table <code>public.target_six</code>.
     */
    public static final TargetSix TARGET_SIX = de.quinscape.domainql.testdomain.tables.TargetSix.TARGET_SIX;

    /**
     * The table <code>public.target_three</code>.
     */
    public static final TargetThree TARGET_THREE = de.quinscape.domainql.testdomain.tables.TargetThree.TARGET_THREE;

    /**
     * The table <code>public.target_two</code>.
     */
    public static final TargetTwo TARGET_TWO = de.quinscape.domainql.testdomain.tables.TargetTwo.TARGET_TWO;
}
