/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "bar_owner", schema = "public", indexes = {
    @Index(name = "pk_bar_owner", unique = true, columnList = "id ASC")
})
public class BarOwner extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = -1566667685;

    private String id;
    private String name;
    private String orgId;

    public BarOwner() {}

    public BarOwner(BarOwner value) {
        this.id = value.id;
        this.name = value.name;
        this.orgId = value.orgId;
    }

    public BarOwner(
        String id,
        String name,
        String orgId
    ) {
        this.id = id;
        this.name = name;
        this.orgId = orgId;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "org_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BarOwner (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(orgId);

        sb.append(")");
        return sb.toString();
    }
}
