/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "source_eight",
    schema = "public"
)
public class SourceEight extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String targetName;
    private Integer targetNum;

    public SourceEight() {}

    public SourceEight(SourceEight value) {
        this.id = value.id;
        this.targetName = value.targetName;
        this.targetNum = value.targetNum;
    }

    public SourceEight(
        String id,
        String targetName,
        Integer targetNum
    ) {
        this.id = id;
        this.targetName = targetName;
        this.targetNum = targetNum;
    }

    /**
     * Getter for <code>public.source_eight.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.source_eight.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.source_eight.target_name</code>.
     */
    @Column(name = "target_name", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getTargetName() {
        return this.targetName;
    }

    /**
     * Setter for <code>public.source_eight.target_name</code>.
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * Getter for <code>public.source_eight.target_num</code>.
     */
    @Column(name = "target_num", nullable = false)
    @NotNull
    public Integer getTargetNum() {
        return this.targetNum;
    }

    /**
     * Setter for <code>public.source_eight.target_num</code>.
     */
    public void setTargetNum(Integer targetNum) {
        this.targetNum = targetNum;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SourceEight other = (SourceEight) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.targetName == null) {
            if (other.targetName != null)
                return false;
        }
        else if (!this.targetName.equals(other.targetName))
            return false;
        if (this.targetNum == null) {
            if (other.targetNum != null)
                return false;
        }
        else if (!this.targetNum.equals(other.targetNum))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.targetName == null) ? 0 : this.targetName.hashCode());
        result = prime * result + ((this.targetNum == null) ? 0 : this.targetNum.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SourceEight (");

        sb.append(id);
        sb.append(", ").append(targetName);
        sb.append(", ").append(targetNum);

        sb.append(")");
        return sb.toString();
    }
}
