/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.pojos;


import de.quinscape.domainql.generic.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "source_seven", schema = "public", indexes = {
    @Index(name = "pk_source_seven", unique = true, columnList = "id ASC")
})
public class SourceSeven extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 1228358952;

    private String id;
    private String target;

    public SourceSeven() {}

    public SourceSeven(SourceSeven value) {
        this.id = value.id;
        this.target = value.target;
    }

    public SourceSeven(
        String id,
        String target
    ) {
        this.id = id;
        this.target = target;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "target", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getTarget() {
        return this.target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SourceSeven (");

        sb.append(id);
        sb.append(", ").append(target);

        sb.append(")");
        return sb.toString();
    }
}
