/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "source_eight", schema = "public", indexes = {
    @Index(name = "pk_source_eight", unique = true, columnList = "id ASC")
})
public class SourceEight extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 996414326;

    private String  id;
    private String  targetName;
    private Integer targetNum;

    public SourceEight() {}

    public SourceEight(SourceEight value) {
        this.id = value.id;
        this.targetName = value.targetName;
        this.targetNum = value.targetNum;
    }

    public SourceEight(
        String  id,
        String  targetName,
        Integer targetNum
    ) {
        this.id = id;
        this.targetName = targetName;
        this.targetNum = targetNum;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "target_name", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getTargetName() {
        return this.targetName;
    }

    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    @Column(name = "target_num", nullable = false, precision = 32)
    @NotNull
    public Integer getTargetNum() {
        return this.targetNum;
    }

    public void setTargetNum(Integer targetNum) {
        this.targetNum = targetNum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SourceEight (");

        sb.append(id);
        sb.append(", ").append(targetName);
        sb.append(", ").append(targetNum);

        sb.append(")");
        return sb.toString();
    }
}
