/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "target_nine_counts", schema = "public")
public class TargetNineCounts extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 1524349661;

    private String targetId;
    private Long   count;

    public TargetNineCounts() {}

    public TargetNineCounts(TargetNineCounts value) {
        this.targetId = value.targetId;
        this.count = value.count;
    }

    public TargetNineCounts(
        String targetId,
        Long   count
    ) {
        this.targetId = targetId;
        this.count = count;
    }

    @Column(name = "target_id", length = 36)
    @Size(max = 36)
    public String getTargetId() {
        return this.targetId;
    }

    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    @Column(name = "count", precision = 64)
    public Long getCount() {
        return this.count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TargetNineCounts (");

        sb.append(targetId);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
