/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.BarOrgRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BarOrg extends TableImpl<BarOrgRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.bar_org</code>
     */
    public static final BarOrg BAR_ORG = new BarOrg();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BarOrgRecord> getRecordType() {
        return BarOrgRecord.class;
    }

    /**
     * The column <code>public.bar_org.id</code>.
     */
    public final TableField<BarOrgRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.bar_org.name</code>.
     */
    public final TableField<BarOrgRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private BarOrg(Name alias, Table<BarOrgRecord> aliased) {
        this(alias, aliased, null);
    }

    private BarOrg(Name alias, Table<BarOrgRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.bar_org</code> table reference
     */
    public BarOrg(String alias) {
        this(DSL.name(alias), BAR_ORG);
    }

    /**
     * Create an aliased <code>public.bar_org</code> table reference
     */
    public BarOrg(Name alias) {
        this(alias, BAR_ORG);
    }

    /**
     * Create a <code>public.bar_org</code> table reference
     */
    public BarOrg() {
        this(DSL.name("bar_org"), null);
    }

    public <O extends Record> BarOrg(Table<O> child, ForeignKey<O, BarOrgRecord> key) {
        super(child, key, BAR_ORG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<BarOrgRecord> getPrimaryKey() {
        return Keys.PK_BAR_ORG;
    }

    @Override
    public BarOrg as(String alias) {
        return new BarOrg(DSL.name(alias), this);
    }

    @Override
    public BarOrg as(Name alias) {
        return new BarOrg(alias, this);
    }

    @Override
    public BarOrg as(Table<?> alias) {
        return new BarOrg(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BarOrg rename(String name) {
        return new BarOrg(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BarOrg rename(Name name) {
        return new BarOrg(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BarOrg rename(Table<?> name) {
        return new BarOrg(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
