/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Indexes;
import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.BarOrgRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BarOrg extends TableImpl<BarOrgRecord> {

    private static final long serialVersionUID = 90633529;

    /**
     * The reference instance of <code>public.bar_org</code>
     */
    public static final BarOrg BAR_ORG = new BarOrg();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BarOrgRecord> getRecordType() {
        return BarOrgRecord.class;
    }

    /**
     * The column <code>public.bar_org.id</code>.
     */
    public final TableField<BarOrgRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.bar_org.name</code>.
     */
    public final TableField<BarOrgRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * Create a <code>public.bar_org</code> table reference
     */
    public BarOrg() {
        this(DSL.name("bar_org"), null);
    }

    /**
     * Create an aliased <code>public.bar_org</code> table reference
     */
    public BarOrg(String alias) {
        this(DSL.name(alias), BAR_ORG);
    }

    /**
     * Create an aliased <code>public.bar_org</code> table reference
     */
    public BarOrg(Name alias) {
        this(alias, BAR_ORG);
    }

    private BarOrg(Name alias, Table<BarOrgRecord> aliased) {
        this(alias, aliased, null);
    }

    private BarOrg(Name alias, Table<BarOrgRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_BAR_ORG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BarOrgRecord> getPrimaryKey() {
        return Keys.PK_BAR_ORG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BarOrgRecord>> getKeys() {
        return Arrays.<UniqueKey<BarOrgRecord>>asList(Keys.PK_BAR_ORG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarOrg as(String alias) {
        return new BarOrg(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarOrg as(Name alias) {
        return new BarOrg(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BarOrg rename(String name) {
        return new BarOrg(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BarOrg rename(Name name) {
        return new BarOrg(name, null);
    }
}
