/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Indexes;
import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.BarOwnerRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BarOwner extends TableImpl<BarOwnerRecord> {

    private static final long serialVersionUID = -723414678;

    /**
     * The reference instance of <code>public.bar_owner</code>
     */
    public static final BarOwner BAR_OWNER = new BarOwner();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BarOwnerRecord> getRecordType() {
        return BarOwnerRecord.class;
    }

    /**
     * The column <code>public.bar_owner.id</code>.
     */
    public final TableField<BarOwnerRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.bar_owner.name</code>.
     */
    public final TableField<BarOwnerRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.bar_owner.org_id</code>.
     */
    public final TableField<BarOwnerRecord, String> ORG_ID = createField("org_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * Create a <code>public.bar_owner</code> table reference
     */
    public BarOwner() {
        this(DSL.name("bar_owner"), null);
    }

    /**
     * Create an aliased <code>public.bar_owner</code> table reference
     */
    public BarOwner(String alias) {
        this(DSL.name(alias), BAR_OWNER);
    }

    /**
     * Create an aliased <code>public.bar_owner</code> table reference
     */
    public BarOwner(Name alias) {
        this(alias, BAR_OWNER);
    }

    private BarOwner(Name alias, Table<BarOwnerRecord> aliased) {
        this(alias, aliased, null);
    }

    private BarOwner(Name alias, Table<BarOwnerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_BAR_OWNER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BarOwnerRecord> getPrimaryKey() {
        return Keys.PK_BAR_OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BarOwnerRecord>> getKeys() {
        return Arrays.<UniqueKey<BarOwnerRecord>>asList(Keys.PK_BAR_OWNER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<BarOwnerRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<BarOwnerRecord, ?>>asList(Keys.BAR_OWNER__FK_BAR_OWNER_ORG_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarOwner as(String alias) {
        return new BarOwner(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BarOwner as(Name alias) {
        return new BarOwner(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BarOwner rename(String name) {
        return new BarOwner(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BarOwner rename(Name name) {
        return new BarOwner(name, null);
    }
}
