/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.SourceThreeRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceThree extends TableImpl<SourceThreeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.source_three</code>
     */
    public static final SourceThree SOURCE_THREE = new SourceThree();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SourceThreeRecord> getRecordType() {
        return SourceThreeRecord.class;
    }

    /**
     * The column <code>public.source_three.id</code>.
     */
    public final TableField<SourceThreeRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.source_three.target_id</code>.
     */
    public final TableField<SourceThreeRecord, String> TARGET_ID = createField(DSL.name("target_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private SourceThree(Name alias, Table<SourceThreeRecord> aliased) {
        this(alias, aliased, null);
    }

    private SourceThree(Name alias, Table<SourceThreeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.source_three</code> table reference
     */
    public SourceThree(String alias) {
        this(DSL.name(alias), SOURCE_THREE);
    }

    /**
     * Create an aliased <code>public.source_three</code> table reference
     */
    public SourceThree(Name alias) {
        this(alias, SOURCE_THREE);
    }

    /**
     * Create a <code>public.source_three</code> table reference
     */
    public SourceThree() {
        this(DSL.name("source_three"), null);
    }

    public <O extends Record> SourceThree(Table<O> child, ForeignKey<O, SourceThreeRecord> key) {
        super(child, key, SOURCE_THREE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SourceThreeRecord> getPrimaryKey() {
        return Keys.PK_SOURCE_THREE;
    }

    @Override
    public List<ForeignKey<SourceThreeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SOURCE_THREE__FK_SOURCE_THREE_TARGET_ID);
    }

    private transient TargetThree _targetThree;

    /**
     * Get the implicit join path to the <code>public.target_three</code> table.
     */
    public TargetThree targetThree() {
        if (_targetThree == null)
            _targetThree = new TargetThree(this, Keys.SOURCE_THREE__FK_SOURCE_THREE_TARGET_ID);

        return _targetThree;
    }

    @Override
    public SourceThree as(String alias) {
        return new SourceThree(DSL.name(alias), this);
    }

    @Override
    public SourceThree as(Name alias) {
        return new SourceThree(alias, this);
    }

    @Override
    public SourceThree as(Table<?> alias) {
        return new SourceThree(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceThree rename(String name) {
        return new SourceThree(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceThree rename(Name name) {
        return new SourceThree(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceThree rename(Table<?> name) {
        return new SourceThree(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
