/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.SourceSevenRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceSeven extends TableImpl<SourceSevenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.source_seven</code>
     */
    public static final SourceSeven SOURCE_SEVEN = new SourceSeven();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SourceSevenRecord> getRecordType() {
        return SourceSevenRecord.class;
    }

    /**
     * The column <code>public.source_seven.id</code>.
     */
    public final TableField<SourceSevenRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.source_seven.target</code>.
     */
    public final TableField<SourceSevenRecord, String> TARGET = createField(DSL.name("target"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private SourceSeven(Name alias, Table<SourceSevenRecord> aliased) {
        this(alias, aliased, null);
    }

    private SourceSeven(Name alias, Table<SourceSevenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.source_seven</code> table reference
     */
    public SourceSeven(String alias) {
        this(DSL.name(alias), SOURCE_SEVEN);
    }

    /**
     * Create an aliased <code>public.source_seven</code> table reference
     */
    public SourceSeven(Name alias) {
        this(alias, SOURCE_SEVEN);
    }

    /**
     * Create a <code>public.source_seven</code> table reference
     */
    public SourceSeven() {
        this(DSL.name("source_seven"), null);
    }

    public <O extends Record> SourceSeven(Table<O> child, ForeignKey<O, SourceSevenRecord> key) {
        super(child, key, SOURCE_SEVEN);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SourceSevenRecord> getPrimaryKey() {
        return Keys.PK_SOURCE_SEVEN;
    }

    @Override
    public List<ForeignKey<SourceSevenRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SOURCE_SEVEN__FK_SOURCE_SEVEN_TARGET);
    }

    private transient TargetSeven _targetSeven;

    /**
     * Get the implicit join path to the <code>public.target_seven</code> table.
     */
    public TargetSeven targetSeven() {
        if (_targetSeven == null)
            _targetSeven = new TargetSeven(this, Keys.SOURCE_SEVEN__FK_SOURCE_SEVEN_TARGET);

        return _targetSeven;
    }

    @Override
    public SourceSeven as(String alias) {
        return new SourceSeven(DSL.name(alias), this);
    }

    @Override
    public SourceSeven as(Name alias) {
        return new SourceSeven(alias, this);
    }

    @Override
    public SourceSeven as(Table<?> alias) {
        return new SourceSeven(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceSeven rename(String name) {
        return new SourceSeven(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceSeven rename(Name name) {
        return new SourceSeven(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceSeven rename(Table<?> name) {
        return new SourceSeven(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
