/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Indexes;
import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.SourceFourRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceFour extends TableImpl<SourceFourRecord> {

    private static final long serialVersionUID = 191792470;

    /**
     * The reference instance of <code>public.source_four</code>
     */
    public static final SourceFour SOURCE_FOUR = new SourceFour();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SourceFourRecord> getRecordType() {
        return SourceFourRecord.class;
    }

    /**
     * The column <code>public.source_four.id</code>.
     */
    public final TableField<SourceFourRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.source_four.target_id</code>.
     */
    public final TableField<SourceFourRecord, String> TARGET_ID = createField("target_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.source_four.target2_id</code>.
     */
    public final TableField<SourceFourRecord, String> TARGET2_ID = createField("target2_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * Create a <code>public.source_four</code> table reference
     */
    public SourceFour() {
        this(DSL.name("source_four"), null);
    }

    /**
     * Create an aliased <code>public.source_four</code> table reference
     */
    public SourceFour(String alias) {
        this(DSL.name(alias), SOURCE_FOUR);
    }

    /**
     * Create an aliased <code>public.source_four</code> table reference
     */
    public SourceFour(Name alias) {
        this(alias, SOURCE_FOUR);
    }

    private SourceFour(Name alias, Table<SourceFourRecord> aliased) {
        this(alias, aliased, null);
    }

    private SourceFour(Name alias, Table<SourceFourRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_SOURCE_FOUR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SourceFourRecord> getPrimaryKey() {
        return Keys.PK_SOURCE_FOUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SourceFourRecord>> getKeys() {
        return Arrays.<UniqueKey<SourceFourRecord>>asList(Keys.PK_SOURCE_FOUR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SourceFourRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SourceFourRecord, ?>>asList(Keys.SOURCE_FOUR__FK_SOURCE_FOUR_TARGET_ID, Keys.SOURCE_FOUR__FK_SOURCE_FOUR_TARGET2_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceFour as(String alias) {
        return new SourceFour(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceFour as(Name alias) {
        return new SourceFour(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceFour rename(String name) {
        return new SourceFour(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceFour rename(Name name) {
        return new SourceFour(name, null);
    }
}
