/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.SourceEightRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceEight extends TableImpl<SourceEightRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.source_eight</code>
     */
    public static final SourceEight SOURCE_EIGHT = new SourceEight();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SourceEightRecord> getRecordType() {
        return SourceEightRecord.class;
    }

    /**
     * The column <code>public.source_eight.id</code>.
     */
    public final TableField<SourceEightRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.source_eight.target_name</code>.
     */
    public final TableField<SourceEightRecord, String> TARGET_NAME = createField(DSL.name("target_name"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.source_eight.target_num</code>.
     */
    public final TableField<SourceEightRecord, Integer> TARGET_NUM = createField(DSL.name("target_num"), SQLDataType.INTEGER.nullable(false), this, "");

    private SourceEight(Name alias, Table<SourceEightRecord> aliased) {
        this(alias, aliased, null);
    }

    private SourceEight(Name alias, Table<SourceEightRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.source_eight</code> table reference
     */
    public SourceEight(String alias) {
        this(DSL.name(alias), SOURCE_EIGHT);
    }

    /**
     * Create an aliased <code>public.source_eight</code> table reference
     */
    public SourceEight(Name alias) {
        this(alias, SOURCE_EIGHT);
    }

    /**
     * Create a <code>public.source_eight</code> table reference
     */
    public SourceEight() {
        this(DSL.name("source_eight"), null);
    }

    public <O extends Record> SourceEight(Table<O> child, ForeignKey<O, SourceEightRecord> key) {
        super(child, key, SOURCE_EIGHT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SourceEightRecord> getPrimaryKey() {
        return Keys.PK_SOURCE_EIGHT;
    }

    @Override
    public List<ForeignKey<SourceEightRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SOURCE_EIGHT__FK_SOURCE_EIGHT_TARGET);
    }

    private transient TargetEight _targetEight;

    /**
     * Get the implicit join path to the <code>public.target_eight</code> table.
     */
    public TargetEight targetEight() {
        if (_targetEight == null)
            _targetEight = new TargetEight(this, Keys.SOURCE_EIGHT__FK_SOURCE_EIGHT_TARGET);

        return _targetEight;
    }

    @Override
    public SourceEight as(String alias) {
        return new SourceEight(DSL.name(alias), this);
    }

    @Override
    public SourceEight as(Name alias) {
        return new SourceEight(alias, this);
    }

    @Override
    public SourceEight as(Table<?> alias) {
        return new SourceEight(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceEight rename(String name) {
        return new SourceEight(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceEight rename(Name name) {
        return new SourceEight(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceEight rename(Table<?> name) {
        return new SourceEight(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
