/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.SourceSixRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceSix extends TableImpl<SourceSixRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.source_six</code>
     */
    public static final SourceSix SOURCE_SIX = new SourceSix();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SourceSixRecord> getRecordType() {
        return SourceSixRecord.class;
    }

    /**
     * The column <code>public.source_six.id</code>.
     */
    public final TableField<SourceSixRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.source_six.target_id</code>.
     */
    public final TableField<SourceSixRecord, String> TARGET_ID = createField(DSL.name("target_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private SourceSix(Name alias, Table<SourceSixRecord> aliased) {
        this(alias, aliased, null);
    }

    private SourceSix(Name alias, Table<SourceSixRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.source_six</code> table reference
     */
    public SourceSix(String alias) {
        this(DSL.name(alias), SOURCE_SIX);
    }

    /**
     * Create an aliased <code>public.source_six</code> table reference
     */
    public SourceSix(Name alias) {
        this(alias, SOURCE_SIX);
    }

    /**
     * Create a <code>public.source_six</code> table reference
     */
    public SourceSix() {
        this(DSL.name("source_six"), null);
    }

    public <O extends Record> SourceSix(Table<O> child, ForeignKey<O, SourceSixRecord> key) {
        super(child, key, SOURCE_SIX);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SourceSixRecord> getPrimaryKey() {
        return Keys.PK_SOURCE_SIX;
    }

    @Override
    public List<ForeignKey<SourceSixRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SOURCE_SIX__FK_SOURCE_SIX_TARGET_ID);
    }

    private transient TargetSix _targetSix;

    /**
     * Get the implicit join path to the <code>public.target_six</code> table.
     */
    public TargetSix targetSix() {
        if (_targetSix == null)
            _targetSix = new TargetSix(this, Keys.SOURCE_SIX__FK_SOURCE_SIX_TARGET_ID);

        return _targetSix;
    }

    @Override
    public SourceSix as(String alias) {
        return new SourceSix(DSL.name(alias), this);
    }

    @Override
    public SourceSix as(Name alias) {
        return new SourceSix(alias, this);
    }

    @Override
    public SourceSix as(Table<?> alias) {
        return new SourceSix(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceSix rename(String name) {
        return new SourceSix(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceSix rename(Name name) {
        return new SourceSix(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceSix rename(Table<?> name) {
        return new SourceSix(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
