/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Indexes;
import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.SourceTwoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceTwo extends TableImpl<SourceTwoRecord> {

    private static final long serialVersionUID = 1407863902;

    /**
     * The reference instance of <code>public.source_two</code>
     */
    public static final SourceTwo SOURCE_TWO = new SourceTwo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SourceTwoRecord> getRecordType() {
        return SourceTwoRecord.class;
    }

    /**
     * The column <code>public.source_two.id</code>.
     */
    public final TableField<SourceTwoRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.source_two.target_id</code>.
     */
    public final TableField<SourceTwoRecord, String> TARGET_ID = createField("target_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * Create a <code>public.source_two</code> table reference
     */
    public SourceTwo() {
        this(DSL.name("source_two"), null);
    }

    /**
     * Create an aliased <code>public.source_two</code> table reference
     */
    public SourceTwo(String alias) {
        this(DSL.name(alias), SOURCE_TWO);
    }

    /**
     * Create an aliased <code>public.source_two</code> table reference
     */
    public SourceTwo(Name alias) {
        this(alias, SOURCE_TWO);
    }

    private SourceTwo(Name alias, Table<SourceTwoRecord> aliased) {
        this(alias, aliased, null);
    }

    private SourceTwo(Name alias, Table<SourceTwoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_SOURCE_TWO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SourceTwoRecord> getPrimaryKey() {
        return Keys.PK_SOURCE_TWO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SourceTwoRecord>> getKeys() {
        return Arrays.<UniqueKey<SourceTwoRecord>>asList(Keys.PK_SOURCE_TWO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SourceTwoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SourceTwoRecord, ?>>asList(Keys.SOURCE_TWO__FK_SOURCE_TWO_TARGET_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceTwo as(String alias) {
        return new SourceTwo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceTwo as(Name alias) {
        return new SourceTwo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceTwo rename(String name) {
        return new SourceTwo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SourceTwo rename(Name name) {
        return new SourceTwo(name, null);
    }
}
