/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.TargetOneRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function1;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TargetOne extends TableImpl<TargetOneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.target_one</code>
     */
    public static final TargetOne TARGET_ONE = new TargetOne();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TargetOneRecord> getRecordType() {
        return TargetOneRecord.class;
    }

    /**
     * The column <code>public.target_one.id</code>.
     */
    public final TableField<TargetOneRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private TargetOne(Name alias, Table<TargetOneRecord> aliased) {
        this(alias, aliased, null);
    }

    private TargetOne(Name alias, Table<TargetOneRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.target_one</code> table reference
     */
    public TargetOne(String alias) {
        this(DSL.name(alias), TARGET_ONE);
    }

    /**
     * Create an aliased <code>public.target_one</code> table reference
     */
    public TargetOne(Name alias) {
        this(alias, TARGET_ONE);
    }

    /**
     * Create a <code>public.target_one</code> table reference
     */
    public TargetOne() {
        this(DSL.name("target_one"), null);
    }

    public <O extends Record> TargetOne(Table<O> child, ForeignKey<O, TargetOneRecord> key) {
        super(child, key, TARGET_ONE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TargetOneRecord> getPrimaryKey() {
        return Keys.PK_TARGET_ONE;
    }

    @Override
    public TargetOne as(String alias) {
        return new TargetOne(DSL.name(alias), this);
    }

    @Override
    public TargetOne as(Name alias) {
        return new TargetOne(alias, this);
    }

    @Override
    public TargetOne as(Table<?> alias) {
        return new TargetOne(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetOne rename(String name) {
        return new TargetOne(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetOne rename(Name name) {
        return new TargetOne(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetOne rename(Table<?> name) {
        return new TargetOne(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function1<? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function1<? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
