/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.TargetEightRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TargetEight extends TableImpl<TargetEightRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.target_eight</code>
     */
    public static final TargetEight TARGET_EIGHT = new TargetEight();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TargetEightRecord> getRecordType() {
        return TargetEightRecord.class;
    }

    /**
     * The column <code>public.target_eight.id</code>.
     */
    public final TableField<TargetEightRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.target_eight.name</code>.
     */
    public final TableField<TargetEightRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.target_eight.num</code>.
     */
    public final TableField<TargetEightRecord, Integer> NUM = createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    private TargetEight(Name alias, Table<TargetEightRecord> aliased) {
        this(alias, aliased, null);
    }

    private TargetEight(Name alias, Table<TargetEightRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.target_eight</code> table reference
     */
    public TargetEight(String alias) {
        this(DSL.name(alias), TARGET_EIGHT);
    }

    /**
     * Create an aliased <code>public.target_eight</code> table reference
     */
    public TargetEight(Name alias) {
        this(alias, TARGET_EIGHT);
    }

    /**
     * Create a <code>public.target_eight</code> table reference
     */
    public TargetEight() {
        this(DSL.name("target_eight"), null);
    }

    public <O extends Record> TargetEight(Table<O> child, ForeignKey<O, TargetEightRecord> key) {
        super(child, key, TARGET_EIGHT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TargetEightRecord> getPrimaryKey() {
        return Keys.PK_TARGET_EIGHT;
    }

    @Override
    public List<UniqueKey<TargetEightRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TARGET_EIGHT_NAME_KEY);
    }

    @Override
    public TargetEight as(String alias) {
        return new TargetEight(DSL.name(alias), this);
    }

    @Override
    public TargetEight as(Name alias) {
        return new TargetEight(alias, this);
    }

    @Override
    public TargetEight as(Table<?> alias) {
        return new TargetEight(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetEight rename(String name) {
        return new TargetEight(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetEight rename(Name name) {
        return new TargetEight(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetEight rename(Table<?> name) {
        return new TargetEight(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
