/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.TargetNineRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TargetNine extends TableImpl<TargetNineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.target_nine</code>
     */
    public static final TargetNine TARGET_NINE = new TargetNine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TargetNineRecord> getRecordType() {
        return TargetNineRecord.class;
    }

    /**
     * The column <code>public.target_nine.id</code>.
     */
    public final TableField<TargetNineRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.target_nine.name</code>.
     */
    public final TableField<TargetNineRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private TargetNine(Name alias, Table<TargetNineRecord> aliased) {
        this(alias, aliased, null);
    }

    private TargetNine(Name alias, Table<TargetNineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.target_nine</code> table reference
     */
    public TargetNine(String alias) {
        this(DSL.name(alias), TARGET_NINE);
    }

    /**
     * Create an aliased <code>public.target_nine</code> table reference
     */
    public TargetNine(Name alias) {
        this(alias, TARGET_NINE);
    }

    /**
     * Create a <code>public.target_nine</code> table reference
     */
    public TargetNine() {
        this(DSL.name("target_nine"), null);
    }

    public <O extends Record> TargetNine(Table<O> child, ForeignKey<O, TargetNineRecord> key) {
        super(child, key, TARGET_NINE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TargetNineRecord> getPrimaryKey() {
        return Keys.PK_TARGET_NINE;
    }

    @Override
    public TargetNine as(String alias) {
        return new TargetNine(DSL.name(alias), this);
    }

    @Override
    public TargetNine as(Name alias) {
        return new TargetNine(alias, this);
    }

    @Override
    public TargetNine as(Table<?> alias) {
        return new TargetNine(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetNine rename(String name) {
        return new TargetNine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetNine rename(Name name) {
        return new TargetNine(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetNine rename(Table<?> name) {
        return new TargetNine(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
