/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.TargetFiveRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function1;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TargetFive extends TableImpl<TargetFiveRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.target_five</code>
     */
    public static final TargetFive TARGET_FIVE = new TargetFive();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TargetFiveRecord> getRecordType() {
        return TargetFiveRecord.class;
    }

    /**
     * The column <code>public.target_five.id</code>.
     */
    public final TableField<TargetFiveRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private TargetFive(Name alias, Table<TargetFiveRecord> aliased) {
        this(alias, aliased, null);
    }

    private TargetFive(Name alias, Table<TargetFiveRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.target_five</code> table reference
     */
    public TargetFive(String alias) {
        this(DSL.name(alias), TARGET_FIVE);
    }

    /**
     * Create an aliased <code>public.target_five</code> table reference
     */
    public TargetFive(Name alias) {
        this(alias, TARGET_FIVE);
    }

    /**
     * Create a <code>public.target_five</code> table reference
     */
    public TargetFive() {
        this(DSL.name("target_five"), null);
    }

    public <O extends Record> TargetFive(Table<O> child, ForeignKey<O, TargetFiveRecord> key) {
        super(child, key, TARGET_FIVE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TargetFiveRecord> getPrimaryKey() {
        return Keys.PK_TARGET_FIVE;
    }

    @Override
    public TargetFive as(String alias) {
        return new TargetFive(DSL.name(alias), this);
    }

    @Override
    public TargetFive as(Name alias) {
        return new TargetFive(alias, this);
    }

    @Override
    public TargetFive as(Table<?> alias) {
        return new TargetFive(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetFive rename(String name) {
        return new TargetFive(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetFive rename(Name name) {
        return new TargetFive(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetFive rename(Table<?> name) {
        return new TargetFive(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function1<? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function1<? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
