/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Indexes;
import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.TargetOneRecord;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TargetOne extends TableImpl<TargetOneRecord> {

    private static final long serialVersionUID = 356433471;

    /**
     * The reference instance of <code>public.target_one</code>
     */
    public static final TargetOne TARGET_ONE = new TargetOne();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TargetOneRecord> getRecordType() {
        return TargetOneRecord.class;
    }

    /**
     * The column <code>public.target_one.id</code>.
     */
    public final TableField<TargetOneRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * Create a <code>public.target_one</code> table reference
     */
    public TargetOne() {
        this(DSL.name("target_one"), null);
    }

    /**
     * Create an aliased <code>public.target_one</code> table reference
     */
    public TargetOne(String alias) {
        this(DSL.name(alias), TARGET_ONE);
    }

    /**
     * Create an aliased <code>public.target_one</code> table reference
     */
    public TargetOne(Name alias) {
        this(alias, TARGET_ONE);
    }

    private TargetOne(Name alias, Table<TargetOneRecord> aliased) {
        this(alias, aliased, null);
    }

    private TargetOne(Name alias, Table<TargetOneRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_TARGET_ONE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TargetOneRecord> getPrimaryKey() {
        return Keys.PK_TARGET_ONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TargetOneRecord>> getKeys() {
        return Arrays.<UniqueKey<TargetOneRecord>>asList(Keys.PK_TARGET_ONE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TargetOne as(String alias) {
        return new TargetOne(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TargetOne as(Name alias) {
        return new TargetOne(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetOne rename(String name) {
        return new TargetOne(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetOne rename(Name name) {
        return new TargetOne(name, null);
    }
}
