/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.TargetSevenRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TargetSeven extends TableImpl<TargetSevenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.target_seven</code>
     */
    public static final TargetSeven TARGET_SEVEN = new TargetSeven();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TargetSevenRecord> getRecordType() {
        return TargetSevenRecord.class;
    }

    /**
     * The column <code>public.target_seven.id</code>.
     */
    public final TableField<TargetSevenRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.target_seven.name</code>.
     */
    public final TableField<TargetSevenRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private TargetSeven(Name alias, Table<TargetSevenRecord> aliased) {
        this(alias, aliased, null);
    }

    private TargetSeven(Name alias, Table<TargetSevenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.target_seven</code> table reference
     */
    public TargetSeven(String alias) {
        this(DSL.name(alias), TARGET_SEVEN);
    }

    /**
     * Create an aliased <code>public.target_seven</code> table reference
     */
    public TargetSeven(Name alias) {
        this(alias, TARGET_SEVEN);
    }

    /**
     * Create a <code>public.target_seven</code> table reference
     */
    public TargetSeven() {
        this(DSL.name("target_seven"), null);
    }

    public <O extends Record> TargetSeven(Table<O> child, ForeignKey<O, TargetSevenRecord> key) {
        super(child, key, TARGET_SEVEN);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TargetSevenRecord> getPrimaryKey() {
        return Keys.PK_TARGET_SEVEN;
    }

    @Override
    public List<UniqueKey<TargetSevenRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TARGET_SEVEN_NAME_KEY);
    }

    @Override
    public TargetSeven as(String alias) {
        return new TargetSeven(DSL.name(alias), this);
    }

    @Override
    public TargetSeven as(Name alias) {
        return new TargetSeven(alias, this);
    }

    @Override
    public TargetSeven as(Table<?> alias) {
        return new TargetSeven(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetSeven rename(String name) {
        return new TargetSeven(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetSeven rename(Name name) {
        return new TargetSeven(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetSeven rename(Table<?> name) {
        return new TargetSeven(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
