/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables;


import de.quinscape.domainql.testdomain.Keys;
import de.quinscape.domainql.testdomain.Public;
import de.quinscape.domainql.testdomain.tables.records.TargetSixRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function1;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TargetSix extends TableImpl<TargetSixRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.target_six</code>
     */
    public static final TargetSix TARGET_SIX = new TargetSix();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TargetSixRecord> getRecordType() {
        return TargetSixRecord.class;
    }

    /**
     * The column <code>public.target_six.id</code>.
     */
    public final TableField<TargetSixRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private TargetSix(Name alias, Table<TargetSixRecord> aliased) {
        this(alias, aliased, null);
    }

    private TargetSix(Name alias, Table<TargetSixRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.target_six</code> table reference
     */
    public TargetSix(String alias) {
        this(DSL.name(alias), TARGET_SIX);
    }

    /**
     * Create an aliased <code>public.target_six</code> table reference
     */
    public TargetSix(Name alias) {
        this(alias, TARGET_SIX);
    }

    /**
     * Create a <code>public.target_six</code> table reference
     */
    public TargetSix() {
        this(DSL.name("target_six"), null);
    }

    public <O extends Record> TargetSix(Table<O> child, ForeignKey<O, TargetSixRecord> key) {
        super(child, key, TARGET_SIX);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TargetSixRecord> getPrimaryKey() {
        return Keys.PK_TARGET_SIX;
    }

    @Override
    public TargetSix as(String alias) {
        return new TargetSix(DSL.name(alias), this);
    }

    @Override
    public TargetSix as(Name alias) {
        return new TargetSix(alias, this);
    }

    @Override
    public TargetSix as(Table<?> alias) {
        return new TargetSix(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetSix rename(String name) {
        return new TargetSix(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetSix rename(Name name) {
        return new TargetSix(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TargetSix rename(Table<?> name) {
        return new TargetSix(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function1<? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function1<? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
