/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables.records;


import de.quinscape.domainql.testdomain.tables.BarOwner;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "bar_owner",
    schema = "public"
)
public class BarOwnerRecord extends UpdatableRecordImpl<BarOwnerRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bar_owner.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bar_owner.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.bar_owner.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bar_owner.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.bar_owner.org_id</code>.
     */
    public void setOrgId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bar_owner.org_id</code>.
     */
    @Column(name = "org_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getOrgId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return BarOwner.BAR_OWNER.ID;
    }

    @Override
    public Field<String> field2() {
        return BarOwner.BAR_OWNER.NAME;
    }

    @Override
    public Field<String> field3() {
        return BarOwner.BAR_OWNER.ORG_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getOrgId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getOrgId();
    }

    @Override
    public BarOwnerRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public BarOwnerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public BarOwnerRecord value3(String value) {
        setOrgId(value);
        return this;
    }

    @Override
    public BarOwnerRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BarOwnerRecord
     */
    public BarOwnerRecord() {
        super(BarOwner.BAR_OWNER);
    }

    /**
     * Create a detached, initialised BarOwnerRecord
     */
    public BarOwnerRecord(String id, String name, String orgId) {
        super(BarOwner.BAR_OWNER);

        setId(id);
        setName(name);
        setOrgId(orgId);
    }

    /**
     * Create a detached, initialised BarOwnerRecord
     */
    public BarOwnerRecord(de.quinscape.domainql.testdomain.tables.pojos.BarOwner value) {
        super(BarOwner.BAR_OWNER);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setOrgId(value.getOrgId());
        }
    }
}
