/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables.records;


import de.quinscape.domainql.testdomain.tables.Bar;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "bar",
    schema = "public"
)
public class BarRecord extends UpdatableRecordImpl<BarRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bar.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bar.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.bar.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bar.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.bar.owner_id</code>.
     */
    public void setOwnerId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bar.owner_id</code>.
     */
    @Column(name = "owner_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getOwnerId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.bar.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bar.description</code>.
     */
    @Column(name = "description")
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Bar.BAR.ID;
    }

    @Override
    public Field<String> field2() {
        return Bar.BAR.NAME;
    }

    @Override
    public Field<String> field3() {
        return Bar.BAR.OWNER_ID;
    }

    @Override
    public Field<String> field4() {
        return Bar.BAR.DESCRIPTION;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getOwnerId();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getOwnerId();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public BarRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public BarRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public BarRecord value3(String value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public BarRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public BarRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BarRecord
     */
    public BarRecord() {
        super(Bar.BAR);
    }

    /**
     * Create a detached, initialised BarRecord
     */
    public BarRecord(String id, String name, String ownerId, String description) {
        super(Bar.BAR);

        setId(id);
        setName(name);
        setOwnerId(ownerId);
        setDescription(description);
    }

    /**
     * Create a detached, initialised BarRecord
     */
    public BarRecord(de.quinscape.domainql.testdomain.tables.pojos.Bar value) {
        super(Bar.BAR);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setOwnerId(value.getOwnerId());
            setDescription(value.getDescription());
        }
    }
}
