/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.records;


import de.quinscape.domainql.testdomain.tables.SourceFour;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "source_four", schema = "public", indexes = {
    @Index(name = "pk_source_four", unique = true, columnList = "id ASC")
})
public class SourceFourRecord extends UpdatableRecordImpl<SourceFourRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 955040777;

    /**
     * Setter for <code>public.source_four.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.source_four.id</code>.
     */
    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.source_four.target_id</code>.
     */
    public void setTargetId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.source_four.target_id</code>.
     */
    @Column(name = "target_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getTargetId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.source_four.target2_id</code>.
     */
    public void setTarget2Id(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.source_four.target2_id</code>.
     */
    @Column(name = "target2_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getTarget2Id() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SourceFour.SOURCE_FOUR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SourceFour.SOURCE_FOUR.TARGET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SourceFour.SOURCE_FOUR.TARGET2_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTargetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTarget2Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTargetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTarget2Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceFourRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceFourRecord value2(String value) {
        setTargetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceFourRecord value3(String value) {
        setTarget2Id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceFourRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourceFourRecord
     */
    public SourceFourRecord() {
        super(SourceFour.SOURCE_FOUR);
    }

    /**
     * Create a detached, initialised SourceFourRecord
     */
    public SourceFourRecord(String id, String targetId, String target2Id) {
        super(SourceFour.SOURCE_FOUR);

        set(0, id);
        set(1, targetId);
        set(2, target2Id);
    }
}
