/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.records;


import de.quinscape.domainql.testdomain.tables.SourceEight;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "source_eight", schema = "public", indexes = {
    @Index(name = "pk_source_eight", unique = true, columnList = "id ASC")
})
public class SourceEightRecord extends UpdatableRecordImpl<SourceEightRecord> implements Record3<String, String, Integer> {

    private static final long serialVersionUID = -688578989;

    /**
     * Setter for <code>public.source_eight.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.source_eight.id</code>.
     */
    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.source_eight.target_name</code>.
     */
    public void setTargetName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.source_eight.target_name</code>.
     */
    @Column(name = "target_name", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getTargetName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.source_eight.target_num</code>.
     */
    public void setTargetNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.source_eight.target_num</code>.
     */
    @Column(name = "target_num", nullable = false, precision = 32)
    @NotNull
    public Integer getTargetNum() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SourceEight.SOURCE_EIGHT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SourceEight.SOURCE_EIGHT.TARGET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SourceEight.SOURCE_EIGHT.TARGET_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTargetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTargetNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTargetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTargetNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceEightRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceEightRecord value2(String value) {
        setTargetName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceEightRecord value3(Integer value) {
        setTargetNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SourceEightRecord values(String value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourceEightRecord
     */
    public SourceEightRecord() {
        super(SourceEight.SOURCE_EIGHT);
    }

    /**
     * Create a detached, initialised SourceEightRecord
     */
    public SourceEightRecord(String id, String targetName, Integer targetNum) {
        super(SourceEight.SOURCE_EIGHT);

        set(0, id);
        set(1, targetName);
        set(2, targetNum);
    }
}
