/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables.records;


import de.quinscape.domainql.testdomain.tables.SourceSeven;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "source_seven",
    schema = "public"
)
public class SourceSevenRecord extends UpdatableRecordImpl<SourceSevenRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.source_seven.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.source_seven.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.source_seven.target</code>.
     */
    public void setTarget(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.source_seven.target</code>.
     */
    @Column(name = "target", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getTarget() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SourceSeven.SOURCE_SEVEN.ID;
    }

    @Override
    public Field<String> field2() {
        return SourceSeven.SOURCE_SEVEN.TARGET;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTarget();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTarget();
    }

    @Override
    public SourceSevenRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SourceSevenRecord value2(String value) {
        setTarget(value);
        return this;
    }

    @Override
    public SourceSevenRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourceSevenRecord
     */
    public SourceSevenRecord() {
        super(SourceSeven.SOURCE_SEVEN);
    }

    /**
     * Create a detached, initialised SourceSevenRecord
     */
    public SourceSevenRecord(String id, String target) {
        super(SourceSeven.SOURCE_SEVEN);

        setId(id);
        setTarget(target);
    }

    /**
     * Create a detached, initialised SourceSevenRecord
     */
    public SourceSevenRecord(de.quinscape.domainql.testdomain.tables.pojos.SourceSeven value) {
        super(SourceSeven.SOURCE_SEVEN);

        if (value != null) {
            setId(value.getId());
            setTarget(value.getTarget());
        }
    }
}
