/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables.records;


import de.quinscape.domainql.testdomain.tables.SourceEight;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "source_eight",
    schema = "public"
)
public class SourceEightRecord extends UpdatableRecordImpl<SourceEightRecord> implements Record3<String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.source_eight.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.source_eight.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.source_eight.target_name</code>.
     */
    public void setTargetName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.source_eight.target_name</code>.
     */
    @Column(name = "target_name", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getTargetName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.source_eight.target_num</code>.
     */
    public void setTargetNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.source_eight.target_num</code>.
     */
    @Column(name = "target_num", nullable = false)
    @NotNull
    public Integer getTargetNum() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SourceEight.SOURCE_EIGHT.ID;
    }

    @Override
    public Field<String> field2() {
        return SourceEight.SOURCE_EIGHT.TARGET_NAME;
    }

    @Override
    public Field<Integer> field3() {
        return SourceEight.SOURCE_EIGHT.TARGET_NUM;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTargetName();
    }

    @Override
    public Integer component3() {
        return getTargetNum();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTargetName();
    }

    @Override
    public Integer value3() {
        return getTargetNum();
    }

    @Override
    public SourceEightRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SourceEightRecord value2(String value) {
        setTargetName(value);
        return this;
    }

    @Override
    public SourceEightRecord value3(Integer value) {
        setTargetNum(value);
        return this;
    }

    @Override
    public SourceEightRecord values(String value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourceEightRecord
     */
    public SourceEightRecord() {
        super(SourceEight.SOURCE_EIGHT);
    }

    /**
     * Create a detached, initialised SourceEightRecord
     */
    public SourceEightRecord(String id, String targetName, Integer targetNum) {
        super(SourceEight.SOURCE_EIGHT);

        setId(id);
        setTargetName(targetName);
        setTargetNum(targetNum);
    }

    /**
     * Create a detached, initialised SourceEightRecord
     */
    public SourceEightRecord(de.quinscape.domainql.testdomain.tables.pojos.SourceEight value) {
        super(SourceEight.SOURCE_EIGHT);

        if (value != null) {
            setId(value.getId());
            setTargetName(value.getTargetName());
            setTargetNum(value.getTargetNum());
        }
    }
}
