/*
 * This file is generated by jOOQ.
 */
package de.quinscape.domainql.testdomain.tables.records;


import de.quinscape.domainql.testdomain.tables.TargetEight;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "target_eight",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "target_eight_name_key", columnNames = { "name", "num" })
    }
)
public class TargetEightRecord extends UpdatableRecordImpl<TargetEightRecord> implements Record3<String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.target_eight.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.target_eight.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.target_eight.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.target_eight.name</code>.
     */
    @Column(name = "name", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.target_eight.num</code>.
     */
    public void setNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.target_eight.num</code>.
     */
    @Column(name = "num", nullable = false)
    @NotNull
    public Integer getNum() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TargetEight.TARGET_EIGHT.ID;
    }

    @Override
    public Field<String> field2() {
        return TargetEight.TARGET_EIGHT.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return TargetEight.TARGET_EIGHT.NUM;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getNum();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getNum();
    }

    @Override
    public TargetEightRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public TargetEightRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TargetEightRecord value3(Integer value) {
        setNum(value);
        return this;
    }

    @Override
    public TargetEightRecord values(String value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TargetEightRecord
     */
    public TargetEightRecord() {
        super(TargetEight.TARGET_EIGHT);
    }

    /**
     * Create a detached, initialised TargetEightRecord
     */
    public TargetEightRecord(String id, String name, Integer num) {
        super(TargetEight.TARGET_EIGHT);

        setId(id);
        setName(name);
        setNum(num);
    }

    /**
     * Create a detached, initialised TargetEightRecord
     */
    public TargetEightRecord(de.quinscape.domainql.testdomain.tables.pojos.TargetEight value) {
        super(TargetEight.TARGET_EIGHT);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setNum(value.getNum());
        }
    }
}
