/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.daos;


import de.quinscape.domainql.testdomain.tables.SourceTwo;
import de.quinscape.domainql.testdomain.tables.records.SourceTwoRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SourceTwoDao extends DAOImpl<SourceTwoRecord, de.quinscape.domainql.testdomain.tables.pojos.SourceTwo, String> {

    /**
     * Create a new SourceTwoDao without any configuration
     */
    public SourceTwoDao() {
        super(SourceTwo.SOURCE_TWO, de.quinscape.domainql.testdomain.tables.pojos.SourceTwo.class);
    }

    /**
     * Create a new SourceTwoDao with an attached configuration
     */
    @Autowired
    public SourceTwoDao(Configuration configuration) {
        super(SourceTwo.SOURCE_TWO, de.quinscape.domainql.testdomain.tables.pojos.SourceTwo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(de.quinscape.domainql.testdomain.tables.pojos.SourceTwo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.quinscape.domainql.testdomain.tables.pojos.SourceTwo> fetchById(String... values) {
        return fetch(SourceTwo.SOURCE_TWO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.quinscape.domainql.testdomain.tables.pojos.SourceTwo fetchOneById(String value) {
        return fetchOne(SourceTwo.SOURCE_TWO.ID, value);
    }

    /**
     * Fetch records that have <code>target_id IN (values)</code>
     */
    public List<de.quinscape.domainql.testdomain.tables.pojos.SourceTwo> fetchByTargetId(String... values) {
        return fetch(SourceTwo.SOURCE_TWO.TARGET_ID, values);
    }
}
