/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.daos;


import de.quinscape.domainql.testdomain.tables.SourceSix;
import de.quinscape.domainql.testdomain.tables.records.SourceSixRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SourceSixDao extends DAOImpl<SourceSixRecord, de.quinscape.domainql.testdomain.tables.pojos.SourceSix, String> {

    /**
     * Create a new SourceSixDao without any configuration
     */
    public SourceSixDao() {
        super(SourceSix.SOURCE_SIX, de.quinscape.domainql.testdomain.tables.pojos.SourceSix.class);
    }

    /**
     * Create a new SourceSixDao with an attached configuration
     */
    @Autowired
    public SourceSixDao(Configuration configuration) {
        super(SourceSix.SOURCE_SIX, de.quinscape.domainql.testdomain.tables.pojos.SourceSix.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(de.quinscape.domainql.testdomain.tables.pojos.SourceSix object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.quinscape.domainql.testdomain.tables.pojos.SourceSix> fetchById(String... values) {
        return fetch(SourceSix.SOURCE_SIX.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.quinscape.domainql.testdomain.tables.pojos.SourceSix fetchOneById(String value) {
        return fetchOne(SourceSix.SOURCE_SIX.ID, value);
    }

    /**
     * Fetch records that have <code>target_id IN (values)</code>
     */
    public List<de.quinscape.domainql.testdomain.tables.pojos.SourceSix> fetchByTargetId(String... values) {
        return fetch(SourceSix.SOURCE_SIX.TARGET_ID, values);
    }
}
