/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.daos;


import de.quinscape.domainql.testdomain.tables.TargetOne;
import de.quinscape.domainql.testdomain.tables.records.TargetOneRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TargetOneDao extends DAOImpl<TargetOneRecord, de.quinscape.domainql.testdomain.tables.pojos.TargetOne, String> {

    /**
     * Create a new TargetOneDao without any configuration
     */
    public TargetOneDao() {
        super(TargetOne.TARGET_ONE, de.quinscape.domainql.testdomain.tables.pojos.TargetOne.class);
    }

    /**
     * Create a new TargetOneDao with an attached configuration
     */
    @Autowired
    public TargetOneDao(Configuration configuration) {
        super(TargetOne.TARGET_ONE, de.quinscape.domainql.testdomain.tables.pojos.TargetOne.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(de.quinscape.domainql.testdomain.tables.pojos.TargetOne object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.quinscape.domainql.testdomain.tables.pojos.TargetOne> fetchById(String... values) {
        return fetch(TargetOne.TARGET_ONE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.quinscape.domainql.testdomain.tables.pojos.TargetOne fetchOneById(String value) {
        return fetchOne(TargetOne.TARGET_ONE.ID, value);
    }
}
