/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.daos;


import de.quinscape.domainql.testdomain.tables.TargetTwo;
import de.quinscape.domainql.testdomain.tables.records.TargetTwoRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TargetTwoDao extends DAOImpl<TargetTwoRecord, de.quinscape.domainql.testdomain.tables.pojos.TargetTwo, String> {

    /**
     * Create a new TargetTwoDao without any configuration
     */
    public TargetTwoDao() {
        super(TargetTwo.TARGET_TWO, de.quinscape.domainql.testdomain.tables.pojos.TargetTwo.class);
    }

    /**
     * Create a new TargetTwoDao with an attached configuration
     */
    @Autowired
    public TargetTwoDao(Configuration configuration) {
        super(TargetTwo.TARGET_TWO, de.quinscape.domainql.testdomain.tables.pojos.TargetTwo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(de.quinscape.domainql.testdomain.tables.pojos.TargetTwo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.quinscape.domainql.testdomain.tables.pojos.TargetTwo> fetchById(String... values) {
        return fetch(TargetTwo.TARGET_TWO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.quinscape.domainql.testdomain.tables.pojos.TargetTwo fetchOneById(String value) {
        return fetchOne(TargetTwo.TARGET_TWO.ID, value);
    }
}
