/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.testdomain.tables.daos;


import de.quinscape.domainql.testdomain.tables.TargetSix;
import de.quinscape.domainql.testdomain.tables.records.TargetSixRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TargetSixDao extends DAOImpl<TargetSixRecord, de.quinscape.domainql.testdomain.tables.pojos.TargetSix, String> {

    /**
     * Create a new TargetSixDao without any configuration
     */
    public TargetSixDao() {
        super(TargetSix.TARGET_SIX, de.quinscape.domainql.testdomain.tables.pojos.TargetSix.class);
    }

    /**
     * Create a new TargetSixDao with an attached configuration
     */
    @Autowired
    public TargetSixDao(Configuration configuration) {
        super(TargetSix.TARGET_SIX, de.quinscape.domainql.testdomain.tables.pojos.TargetSix.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(de.quinscape.domainql.testdomain.tables.pojos.TargetSix object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.quinscape.domainql.testdomain.tables.pojos.TargetSix> fetchById(String... values) {
        return fetch(TargetSix.TARGET_SIX.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.quinscape.domainql.testdomain.tables.pojos.TargetSix fetchOneById(String value) {
        return fetchOne(TargetSix.TARGET_SIX.ID, value);
    }
}
